version: '3'

services:
  redis:
    image: redis
    container_name: redis-auto-corrections
    command: redis-server --requirepass growdev2022
    ports:
      - 6379:6379
    networks:
      - autocorrections

networks:
  autocorrections:
    driver: bridge

